blank_issues_enabled: false
contact_links:
  - name: UnQCoder related issues
    url: https://github.com/Sandeepgaddam5432/UnQCoder/issues/new/choose
    about: Report issues related to UnQCoder
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other Bolt.diy users.
